### ISSUE TITLE
Possible minor error in GetCR0

### ISSUE THREAD

**Issue by electric-socket** [TheLazyTomcat/lib.SimpleCPUID#1]
In this function, on line 569:
```
  Function GetCR0: NativeUInt; assembler; register;
  asm
  // CR0 is not accessible in user mode (this function will cause exception).
  // If anyone have any idea on how to read CR0 from normal program, let me know.
  {$IFDEF x64}
    DB  $0F, $20, $C0   // MOV  RAX,  CR0 (problems in FPC before 3.0)
  {$ELSE}
    MOV     EAX,  CR0
  {$ENDIF}
  end;  
```
I believe the MOV instruction should be
```
    MOV     RAX,  CR0
```
As far as using this (since it uses a privileged register), have you considered setting up a Linux distribution, install Free Pascal, write a test rig, then sudo the program? Or in the alternative, compile it and a test rig on Windows, then run it using "run as Administrator"?

Skip the last one, running as Administrator doesn't work either. I just tried it. Oh well.

**Comment by TheLazyTomcat** [comment]
No, the line 569 is conditionally compiled only in x86 (ie. 32bit) mode, where there is no RAX register and the CR0 is 32bits wide.
I do not have much experience with more advanced ia32 stuff, but afaik the instruction itself is privileged (it is not normal MOV instruction) - it can only be executed at privilege level 0 - that is, by operating system's kernel, not by any program, irrespective of how high rights it gets.
Anyway the functionality of GetCR0 was replaced by GetMSW, so I should probably remove it.
